[project]
name = "automationcar-orge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "lgpio>=0.2.2.0",
    "opencv-python>=4.13.0.90",
    "pyyaml>=6.0.3",
    "uvicorn>=0.40.0",
]
